"""Fixed taxonomy batches for scan-all without an external VLM."""

COCO_CATEGORIES: list[str] = [
    "person",
    "bicycle",
    "car",
    "motorcycle",
    "airplane",
    "bus",
    "train",
    "truck",
    "boat",
    "traffic light",
    "fire hydrant",
    "stop sign",
    "parking meter",
    "bench",
    "bird",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
    "backpack",
    "umbrella",
    "handbag",
    "tie",
    "suitcase",
    "frisbee",
    "skis",
    "snowboard",
    "sports ball",
    "kite",
    "baseball bat",
    "baseball glove",
    "skateboard",
    "surfboard",
    "tennis racket",
    "bottle",
    "wine glass",
    "cup",
    "fork",
    "knife",
    "spoon",
    "bowl",
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hot dog",
    "pizza",
    "donut",
    "cake",
    "chair",
    "couch",
    "potted plant",
    "bed",
    "dining table",
    "toilet",
    "tv",
    "laptop",
    "mouse",
    "remote",
    "keyboard",
    "cell phone",
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "book",
    "clock",
    "vase",
    "scissors",
    "teddy bear",
    "hair drier",
    "toothbrush",
]

INDOOR_EXTRAS: list[str] = [
    "mug",
    "monitor",
    "headphones",
    "pen",
    "notebook",
    "lamp",
    "plant",
    "window",
    "door",
    "picture frame",
    "power outlet",
    "charger",
    "water bottle",
    "backpack",
    "glasses",
    "watch",
    "wallet",
    "keys",
    "speaker",
    "tablet",
]

OUTDOOR_EXTRAS: list[str] = [
    "tree",
    "flower",
    "sign",
    "building",
    "street",
    "sidewalk",
    "fence",
    "mailbox",
    "bicycle rack",
    "scooter",
]

BATCH_SIZE = 20


def taxonomy_batches() -> list[list[str]]:
    combined = list(dict.fromkeys(COCO_CATEGORIES + INDOOR_EXTRAS + OUTDOOR_EXTRAS))
    return [combined[index : index + BATCH_SIZE] for index in range(0, len(combined), BATCH_SIZE)]


def default_scan_categories(limit: int = 40) -> list[str]:
    combined = list(dict.fromkeys(COCO_CATEGORIES[: limit // 2] + INDOOR_EXTRAS[: limit // 4] + OUTDOOR_EXTRAS[: limit // 4]))
    return combined[:limit]
